# Generated by Django 5.0.6 on 2024-07-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estabelecimentos'),
        ),
    ]
