# Generated by Django 5.0.6 on 2024-07-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_estabelecimento_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='instagram',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
