# Generated by Django 5.0.6 on 2024-07-01 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(help_text='Insira uma data para agenda')),
                ('horario', models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00'), ('6', '12:00 ás 13:00'), ('7', '13:00 ás 14:00'), ('8', '14:00 ás 15:00'), ('9', '15:00 ás 16:00'), ('10', '16:00 ás 17:00'), ('11', '17:00 ás 18:00'), ('12', '18:00 ás 19:00'), ('13', '19:00 ás 20:00'), ('14', '20:00 ás 21:00'), ('15', '21:00 ás 22:00'), ('16', '22:00 ás 23:00'), ('17', '23:00 ás 00:00')], max_length=10)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
